# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b754a15f684e80cc45e098b7f9cd7b0bd467450e3ea847eaa919878eea789698a43a1501507f87403ffdafac927b1a4b12c8501532f3d1b3d278baab52ee5d6

test:
  secret_key_base: 937c93355c439a06de4f0c48cf30c5424c10dd92876bd8794e46625e60c614f76a3c61101001dd839650705cdb853e1c7d72e1c8b0ff1b6afae60ba9868a6469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
